name: Feature Request
description: Suggest a new feature or enhancement for Vigil Guard
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - tbartel74

body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for suggesting a feature!

        We appreciate your ideas for improving Vigil Guard. Please provide as much detail as possible to help us understand your proposal.

        **Note**: This template is for feature requests. For bug reports, please use the Bug Report template.

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
      placeholder: |
        Example: "As a security analyst, I need to export threat detection reports to CSV format for compliance audits. Currently, I have to manually copy data from Grafana, which is time-consuming and error-prone."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution. How should this feature work?
      placeholder: |
        Example: "Add an 'Export Report' button in the Monitoring dashboard that generates a CSV file with:
        - Date range selector (last 7/30/90 days)
        - Columns: timestamp, event_id, threat_score, final_status, detection_category
        - Filters: status (BLOCKED/SANITIZED/ALLOWED), threat level (CRITICAL/HIGH/MEDIUM/LOW)"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of Vigil Guard would this feature impact?
      options:
        - Web UI - Frontend
        - Web UI - Backend API
        - n8n Workflow Engine
        - Prompt Guard API
        - ClickHouse / Monitoring
        - Grafana Dashboards
        - Configuration System
        - Documentation
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my use case)
        - High (significant improvement to workflow)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Example: "I tried using Grafana's native export, but it doesn't include all the metadata we need. Manual SQL queries to ClickHouse are possible but require technical expertise."
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases or scenarios where this feature would be valuable
      placeholder: |
        Use Case 1: Compliance reporting for quarterly audits
        Use Case 2: Sharing threat intelligence with security team
        Use Case 3: Analyzing detection patterns for tuning thresholds
    validations:
      required: false

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: (Optional) Do you have ideas about how this could be implemented?
      placeholder: |
        Example:
        - Add new endpoint: GET /api/reports/export?start=...&end=...&format=csv
        - Frontend: New "Reports" tab with date pickers and export button
        - Backend: Query ClickHouse events_processed table, stream CSV response
        - Consider using Papa Parse library for CSV generation
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Wireframes
      description: (Optional) Add any mockups, wireframes, or visual references
      placeholder: "Drag and drop images here, or provide links to design files"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references
      placeholder: |
        Example:
        - Similar feature in other tools: Splunk's "Export Results" functionality
        - Related documentation: https://docs.vigilguard.local/monitoring
        - Community discussion: link to GitHub Discussions thread
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I am willing to submit a pull request for this feature
        - label: I can help with testing and validation
        - label: I can help with documentation
        - label: I can provide feedback on implementation

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: I have clearly described the problem this feature solves
          required: true
        - label: This feature aligns with Vigil Guard's defensive security mission
          required: true
        - label: I have reviewed the roadmap and contributing guidelines
          required: false
