/**
 * Type declarations for generated documentation manifest
 *
 * Generated by: scripts/generate-docs-manifest.js
 * Source: public/docs/**\/*.md
 */

export interface DocManifestEntry {
  /** Relative path from public/docs/ (e.g., "architecture/architecture.md") */
  path: string;

  /** Filename without extension (e.g., "architecture") */
  file: string;

  /** Parent directory name (e.g., "architecture" or "." for root) */
  directory: string;

  /** Full URL path for fetching (e.g., "/ui/docs/architecture/architecture.md") */
  url: string;

  /** Extracted title from first H1 heading */
  title: string;

  /** Category for grouping (derived from directory) */
  category: string;

  /** File size in bytes */
  size: number;

  /** ISO 8601 modification timestamp */
  modified: string;
}

export interface DocsManifest {
  /** ISO 8601 generation timestamp */
  generated: string;

  /** Total number of documents */
  count: number;

  /** Array of all discovered markdown files */
  documents: DocManifestEntry[];
}
