// Plugin Configuration API Routes
// Provides endpoints for browser extension auto-configuration

import express, { RequestHandler } from 'express';
import { randomBytes } from 'crypto';
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { getPluginConfig, savePluginConfig } from './pluginConfigOps.js';
import { authenticateToken } from './auth.js';

// Token file path (persisted in mounted config volume)
const TOKEN_FILE = '/config/.webhook-token';

/**
 * Create plugin config router with rate limiting
 * @param pluginConfigLimiter - Rate limiter middleware for public endpoint
 */
export default function createPluginConfigRouter(pluginConfigLimiter: RequestHandler) {
  const router = express.Router();

  /**
   * GET /api/plugin-config
   * Public endpoint - browser extension fetches configuration
   * NO AUTHENTICATION REQUIRED (plugin needs access on first install)
   * RATE LIMITED: 10 requests per minute per IP
   */
  router.get('/plugin-config', pluginConfigLimiter, async (req, res) => {
  try {
    const config = await getPluginConfig();

    // Return only public fields (no internal metadata)
    res.json({
      webhookUrl: config.webhookUrl,
      enabled: config.enabled,
      version: config.version,
      webhookAuthToken: config.webhookAuthToken,
      webhookAuthHeader: config.webhookAuthHeader
    });

    console.log('[Plugin Config API] Configuration fetched by extension');
  } catch (error: any) {
    console.error('[Plugin Config API] Failed to fetch config:', error);
    res.status(500).json({
      error: 'Failed to fetch plugin configuration',
      message: error.message
    });
  }
});

/**
 * GET /api/plugin-config/settings
 * Protected endpoint - admin UI fetches full configuration
 * REQUIRES AUTHENTICATION
 */
router.get('/plugin-config/settings', authenticateToken, async (req, res) => {
  try {
    const config = await getPluginConfig();

    // Return full configuration including metadata
    res.json(config);

    console.log('[Plugin Config API] Settings fetched by admin');
  } catch (error: any) {
    console.error('[Plugin Config API] Failed to fetch settings:', error);
    res.status(500).json({
      error: 'Failed to fetch plugin settings',
      message: error.message
    });
  }
});

/**
 * POST /api/plugin-config/settings
 * Protected endpoint - admin UI updates configuration
 * REQUIRES AUTHENTICATION
 */
router.post('/plugin-config/settings', authenticateToken, async (req, res) => {
  try {
    const { webhookUrl, enabled } = req.body;
    const username = (req as any).user?.username || 'unknown';

    // Validate required fields (guiUrl no longer required - removed from UI)
    if (!webhookUrl) {
      return res.status(400).json({
        error: 'Missing required fields',
        message: 'webhookUrl is required'
      });
    }

    // Save configuration
    await savePluginConfig(
      {
        webhookUrl,
        enabled: enabled !== undefined ? Boolean(enabled) : true
      },
      username
    );

    // Fetch updated config to return
    const updatedConfig = await getPluginConfig();

    res.json({
      success: true,
      config: updatedConfig
    });

    console.log(`[Plugin Config API] Settings updated by ${username}`);
  } catch (error: any) {
    console.error('[Plugin Config API] Failed to save settings:', error);
    res.status(500).json({
      error: 'Failed to save plugin settings',
      message: error.message
    });
  }
});

/**
 * POST /api/plugin-config/regenerate-token
 * Protected endpoint - generates new webhook auth token
 * REQUIRES AUTHENTICATION
 * WARNING: After regeneration, user must manually update n8n credentials!
 */
router.post('/plugin-config/regenerate-token', authenticateToken, async (req, res) => {
  try {
    const username = (req as any).user?.username || 'unknown';

    // Generate new 32-character token
    const newToken = randomBytes(24).toString('base64').replace(/[/+=]/g, '').slice(0, 32);

    // Save to file (persisted in mounted config volume)
    writeFileSync(TOKEN_FILE, newToken, 'utf8');

    console.log(`[Plugin Config API] Webhook token regenerated by ${username}`);

    res.json({
      success: true,
      token: newToken,
      message: 'Token regenerated. You must manually update n8n Webhook node credentials with this new token.'
    });
  } catch (error: any) {
    console.error('[Plugin Config API] Failed to regenerate token:', error);
    res.status(500).json({
      error: 'Failed to regenerate token',
      message: error.message
    });
  }
});

  return router;
}
