name: vigil-guard

networks:
  vigil-net:
    external: true
    name: vigil-net

services:
  vigil-web-ui-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vigil-web-ui-frontend
    ports:
      - "5173:80"
    networks:
      - vigil-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  vigil-web-ui-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vigil-web-ui-backend
    command: ["npm","run","dev"]
    ports:
      - "8787:8787"
    environment:
      - NODE_ENV=development
      - TARGET_DIR=${TARGET_DIR:-../../vigil_data/workflow/config}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-vigil-clickhouse}
      - CLICKHOUSE_PORT=${CLICKHOUSE_HTTP_PORT:-8123}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-admin}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-admin123}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DB:-n8n_logs}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ../../vigil_data/workflow/config:/config:rw
    networks:
      - vigil-net
