name: vigil-guard

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.1
    container_name: vigil-clickhouse
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123"   # HTTP API
      - "${CLICKHOUSE_TCP_PORT:-9000}:9000"   # Native TCP
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-n8n_logs}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-admin}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-admin123}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT:-1}
    volumes:
      - ../../vigil_data/clickhouse:/var/lib/clickhouse
      - ./sql/01-create-tables.sql:/docker-entrypoint-initdb.d/01-create-tables.sql:ro
      - ./sql/02-create-views.sql:/docker-entrypoint-initdb.d/02-create-views.sql:ro
    networks:
      - vigil-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: vigil-grafana
    environment:
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS:-vertamedia-clickhouse-datasource}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin123}
      - GF_SECURITY_ALLOW_EMBEDDING=${GF_SECURITY_ALLOW_EMBEDDING:-true}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED:-false}
    ports:
      - "${GF_SERVER_HTTP_PORT:-3001}:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ../../vigil_data/grafana:/var/lib/grafana
    networks:
      - vigil-net
    restart: unless-stopped
    depends_on:
      - clickhouse
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  vigil-net:
    external: true
    name: vigil-net